# Generated by Django 4.1.7 on 2023-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_orderitems_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
