# Generated by Django 4.1.7 on 2023-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_alter_order_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="unique_id",
        ),
        migrations.AddField(
            model_name="order",
            name="unique_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
