# Generated by Django 4.1.7 on 2023-03-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_remove_orderitems_unique_id_order_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="track",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Pending",
                max_length=200,
            ),
        ),
    ]
